M48
; DRILL file {KiCad 6.0.5-a6ca702e91~116~ubuntu22.04.1} date Sun 26 Jun 2022 04:54:08 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-26T16:54:08-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5-a6ca702e91~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
%
G90
G05
T1
X3.7638Y-3.0079
T0
M30
