M48
; DRILL file {KiCad 6.0.9-8da3e8f707~116~ubuntu22.04.1} date Mon 05 Dec 2022 02:03:30 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-05T14:03:30-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.750
%
G90
G05
T1
X77.0Y-82.8
T2
X70.65Y-80.725
X70.65Y-83.475
T0
M30
