M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu20.04.1} date Wed 30 Mar 2022 04:12:37 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-30T16:12:37-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.800
%
G90
G05
T1
X121.975Y-86.525
X162.575Y-90.125
T2
X151.25Y-82.875
T0
M30
