// SquareLine LVGL GENERATED FILE
// EDITOR VERSION: SquareLine Studio 1.1.1
// LVGL VERSION: 8.2.0
// PROJECT: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_COMP_H
#define _SQUARELINE_PROJECT_UI_COMP_H

#include "ui.h"

lv_obj_t * ui_comp_get_child(lv_obj_t * comp, uint32_t child_idx);
extern uint32_t LV_EVENT_GET_COMP_CHILD;

// COMPONENT Card Base
#define UI_COMP_CARD_BASE_CARD_BASE 0
#define UI_COMP_CARD_BASE_CARD_HERO 1
#define UI_COMP_CARD_BASE_CARD_CONTAINER 2
#define UI_COMP_CARD_BASE_CARD_CONTENT_TEXT 3
#define UI_COMP_CARD_BASE_CARD_MORE_TEXT 4
#define _UI_COMP_CARD_BASE_NUM 5
lv_obj_t * ui_Card_Base_create(lv_obj_t * comp_parent);

// COMPONENT Card Title With Icon
#define UI_COMP_CARD_TITLE_WITH_ICON_CARD_TITLE_WITH_ICON 0
#define UI_COMP_CARD_TITLE_WITH_ICON_CARD_TITLE_ICON 1
#define UI_COMP_CARD_TITLE_WITH_ICON_CARD_TITLE_TEXT 2
#define _UI_COMP_CARD_TITLE_WITH_ICON_NUM 3
lv_obj_t * ui_Card_Title_With_Icon_create(lv_obj_t * comp_parent);

// COMPONENT Card title no icon
#define UI_COMP_CARD_TITLE_NO_ICON_CARD_TITLE_NO_ICON 0
#define UI_COMP_CARD_TITLE_NO_ICON_CARD_TITLE_TEXT 1
#define _UI_COMP_CARD_TITLE_NO_ICON_NUM 2
lv_obj_t * ui_Card_title_no_icon_create(lv_obj_t * comp_parent);

// COMPONENT ContainerBelowHeader
#define UI_COMP_CONTAINERBELOWHEADER_CONTAINERBELOWHEADER 0
#define _UI_COMP_CONTAINERBELOWHEADER_NUM 1
lv_obj_t * ui_ContainerBelowHeader_create(lv_obj_t * comp_parent);

// COMPONENT NotificationCard
#define UI_COMP_NOTIFICATIONCARD_NOTIFICATIONCARD 0
#define UI_COMP_NOTIFICATIONCARD_CARD_BASE2 1
#define UI_COMP_NOTIFICATIONCARD_CARD_HERO 2
#define UI_COMP_NOTIFICATIONCARD_CARD_TITLE_WITH_ICON1 3
#define UI_COMP_NOTIFICATIONCARD_CARD_TITLE_ICON 4
#define UI_COMP_NOTIFICATIONCARD_CARD_TITLE_TEXT 5
#define UI_COMP_NOTIFICATIONCARD_CARD_CONTAINER 6
#define UI_COMP_NOTIFICATIONCARD_CARD_CONTENT_TEXT 7
#define UI_COMP_NOTIFICATIONCARD_CARD_MORE_TEXT 8
#define _UI_COMP_NOTIFICATIONCARD_NUM 9
lv_obj_t * ui_NotificationCard_create(lv_obj_t * comp_parent);

// COMPONENT Telescope Header
#define UI_COMP_TELESCOPE_HEADER_TELESCOPE_HEADER 0
#define UI_COMP_TELESCOPE_HEADER_HEADER_TEXT 1
#define UI_COMP_TELESCOPE_HEADER_INDICATORS 2
#define UI_COMP_TELESCOPE_HEADER_BATTERY_INDICATOR 3
#define UI_COMP_TELESCOPE_HEADER_WIFI_INDICATOR 4
#define _UI_COMP_TELESCOPE_HEADER_NUM 5
lv_obj_t * ui_Telescope_Header_create(lv_obj_t * comp_parent);

// COMPONENT card no icon
#define UI_COMP_CARD_NO_ICON_CARD_NO_ICON 0
#define UI_COMP_CARD_NO_ICON_CARD_BASE2 1
#define UI_COMP_CARD_NO_ICON_CARD_HERO 2
#define UI_COMP_CARD_NO_ICON_CARD_CONTAINER 3
#define UI_COMP_CARD_NO_ICON_CARD_TITLE_NO_ICON2 4
#define UI_COMP_CARD_NO_ICON_CARD_TITLE_TEXT 5
#define UI_COMP_CARD_NO_ICON_CARD_CONTENT_TEXT 6
#define UI_COMP_CARD_NO_ICON_CARD_MORE_TEXT 7
#define _UI_COMP_CARD_NO_ICON_NUM 8
lv_obj_t * ui_card_no_icon_create(lv_obj_t * comp_parent);

#endif
