M48
; DRILL file {KiCad 6.0.5-a6ca702e91~116~ubuntu22.04.1} date Fri 01 Jul 2022 09:19:14 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-01T21:19:14-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5-a6ca702e91~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.800
%
G90
G05
T1
X121.975Y-86.525
X162.575Y-90.125
T2
X151.25Y-82.875
T0
M30
